# permissions for end users to edit checkweathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkweather-editor-role
rules:
- apiGroups:
  - weather-app.example.com
  resources:
  - checkweathers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weather-app.example.com
  resources:
  - checkweathers/status
  verbs:
  - get
