# permissions for end users to view checkweathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkweather-viewer-role
rules:
- apiGroups:
  - weather-app.example.com
  resources:
  - checkweathers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weather-app.example.com
  resources:
  - checkweathers/status
  verbs:
  - get
